### ISSUE TITLE
Decide which lectures are free preview

### ISSUE THREAD

**Issue by vegantriathlete** [LearningDevOps/intro-to-devops#8]
I have committed all of my scripts to the repository.

We need to know which lectures will be set as free previews so that we know which videos to commit to the repository. I think it's important that we have at least one free preview lecture for each of us. The welcome to the course lecture will be free preview and I am not counting that one as one of the free previews for either of us.

I'm assigning this to you, even though we will discuss this together. I just want to make sure that you get pinged via email about this issue.

**Comment by vegantriathlete** [comment]
I think we should have this discussion via Blab.

**Comment by vegantriathlete** [comment]
I think a good candidate for my free lecture is the Getting Started lecture.

**Comment by vegantriathlete** [comment]
Maybe a good candidate for you free lecture(s) is the benefits of implementing DevOps.

**Comment by vegantriathlete** [comment]
I guess I already started having the discussion via the comments in the issue. So, I suppose it's fine for us to continue the discussion this way. Maybe we don't need to have a Blab.

**Comment by akshatgoel** [comment]
I am confused on same thought. Benefits one may make sense from "buyer-value" perspective. It is valuable to know how DevOps helps an organization (which makes it a non-preview candidate). At the same time, it gives user idea if course is right for him or not (which makes it a preview candidate).

Or...

We could give any particular type of tool's lecture as preview lecture. The way I like to think is students use the lecture to judge if course is right for him and if instructors are compatible with his style of learning. I guess we can give both these points from any good tool lecture.

**Comment by vegantriathlete** [comment]
I'm not too concerned about which of your lecture(s) you make a free preview. If you'd like to choose one or two of the tools lecture that's fine as well.

**Comment by akshatgoel** [comment]
Great! I think we can close down this issue. If later, we realize that any of the lecture may give wrong impression or drive away students, we can reopen it.
